Algoritmo "DigitarEndereço"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/10/2022
Var
// Seção de Declarações das variáveis 
endereco : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite seu endereço: ")
leia (endereco)
escreva ("Endereço: " + endereco)

Fimalgoritmo