Algoritmo "ImprimeRepitaAte10a1"
// Lógica de Programação]
// Professor   : Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/11/2022
Var
// Seção de Declarações das variáveis 
j : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Imprimindo de 10 a 1 Repita Ate")
   j <- 10
   repita
     escreval (j)
     j <- j-1
     ate j < 1

Fimalgoritmo