Algoritmo "ImprimeEnquanto1a10"
// Lógica de Programação]
// Professor   : Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/11/2022
Var
// Seção de Declarações das variáveis 
j : inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Imprimindo de 1 a 10 com enquanto")
   j <- 1;
   enquanto j < 11 faca
   escreval (j)
   j <- j+1;
   fimenquanto

Fimalgoritmo