Algoritmo "Multiplosde2"
// Lógica de Programação]
// Professor   : Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/11/2022
Var
// Seção de Declarações das variáveis 
j : inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreval ("Multiplos de 2 de 0 a 100")
   para j de 1 ate 100 faca
   se (j%2=0) entao
      escreval (j)
      
   fimse
   fimpara

Fimalgoritmo