Algoritmo "SomarNumerosInteiros"
// Lógica de Programação]
// Professor   : Marcos Monteiro 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/11/2022
Var
// Seção de Declarações das variáveis 
j, n : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   n <- 1
   repita
       escreva (j + n, " + ")
       j <- j + 1
   ate j = 100
       escreva ("Soma total: " )
Fimalgoritmo